version: '3.1'

services:

  wordpress:
    depends_on:
      - db
    image: wordpress:5.4.2-php7.2-apache
    links:
      - db
    ports:
      - 8000:80
    env_file: env/local/wp.env
    volumes:
      - ./wp:/var/www/html/

  wpcli:
    depends_on:
      - wordpress
    image: wordpress:cli-php7.3
    user: xfs #mapping www-data
    links:
      - db
    env_file: env/local/wp.env
    command: "--info"
    volumes:
      - ./wp:/var/www/html/

  db:
    image: mysql:5.7
    volumes:
      - "./.data/db:/var/lib/mysql"
    env_file: env/local/db.env
    command: --default-authentication-plugin=mysql_native_password

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    env_file: env/local/phpmyadmin.env
    links:
       - db
    ports:
      - 8080:80

  mailcatcher:
    image: schickling/mailcatcher:latest
    env_file: env/local/mail.env
    ports:
      - 1080:1080
    tty: true
