version: '3'
services:
  app:
    image: markoshust/magento-nginx:1.18-2
    links:
      - phpfpm
      - mail
      - db
    volumes: &appvolumes
      - ./configs/certs:/etc/nginx/certs
      - ./configs/ca-certs:/usr/local/share/ca-certificates/
      - ./configs/new-nginx.conf:/etc/nginx/conf.d/default.conf
      - ./configs/php-mail.conf:/usr/local/etc/php/conf.d/mail.ini
      - ./configs/php-custom.ini:/usr/local/etc/php/conf.d/php-custom.ini
      - ./commands/setup-config:/usr/local/bin/setup-config
      - ./commands/setup.sh:/var/www/html/bin/setup.sh
      - ./commands/sample-data-install.sh:/var/www/html/bin/sample-data-install.sh
      - ./webroot:/var/www/html/
      - sockdata:/sock
    ports:
      - "80:8000"
      - "443:8443"
      # - "8080:8000"

  phpfpm:
    build:
      context: ./docker/php-fpm-7.3
    links:
      - db
      - mail
    volumes: *appvolumes

    env_file:
      - .env
      - env/php.env
      - env/magento.env
      - env/mysql.env

  db:
    image: mysql:5.7
    ports:
      - 8001:3306
    env_file: env/mysql.env
    volumes:
      - /var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    env_file: env/phpmyadmin.env
    links:
      - db
    ports:
     - 8010:80
    volumes:
     - /sessions

  varnish:
    image: million12/varnish
    links:
      - app
      - phpfpm
    ports:
      - 8080:80
    volumes:
      - ./configs/varnish.vcl:/etc/varnish/default.vcl
    environment:
      - VLC_CONFIG=/etc/varnish/default.vcl

  mail:
    image: mailhog/mailhog
    ports:
      - 8025:8025

  redis:
    image: redis

volumes:
  sockdata:
